### ISSUE TITLE
Is their a contributors guide?

### ISSUE THREAD

**Issue by the123saurav** [tonivade/claudb#145]
Hi folks, was just wondering if you are open to contributions?
If yes, is there a guide?

**Comment by tonivade** [comment]
Hi @the123saurav,

I don't have much time to dedicate to this project, so it's more or less on maintenance mode. In the last 3 months I started a refactor to make it more oriented to testing (as many of the people is using this project for integration testing), but I'm pretty sure I'm not going to implement new commands.

But, answering your question, yes is open from contributions, but no, there's no contributors guide sorry. If you have any question, I will be glad to answer them.
