### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by horaoen** [tonivade/claudb#156]
- I'm not familiar with gradle, and there is the build error message: <img width="1114" alt="image" src="https://github.com/tonivade/claudb/assets/92006580/4fdcb0ba-f76f-432f-b387-f30d0fd76d2d">
- I'm using `./gradlew buld` in the project root path
- using the Intellij IDEA gradle build tools also have the same error.

**Comment by tonivade** [comment]
Sorry, but I cannot reproduce the issue:

The release 1.3.0 of this plugin exists: https://plugins.gradle.org/plugin/io.github.gradle-nexus.publish-plugin/1.3.0

And the ci pipeline I executed now worked without problems: https://github.com/tonivade/claudb/actions/runs/5309835831/jobs/9611019628

**Comment by horaoen** [comment]
> Sorry, but I cannot reproduce the issue:
> 
> The release 1.3.0 of this plugin exists: https://plugins.gradle.org/plugin/io.github.gradle-nexus.publish-plugin/1.3.0
> 
> And the ci pipeline I executed now worked without problems: https://github.com/tonivade/claudb/actions/runs/5309835831/jobs/9611019628

I have resolved it. Anyway, thankyou very much.
