### ISSUE TITLE
org.luaj.vm2.LuaError: script:1 vm error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by chenjianboKeyboard** [tonivade/claudb#36]
hi, when I test 
` jedis.eval("if redis.call('get',KEYS[1]) == ARGV[1] then return redis.call('del',KEYS[1]) else return 0 end", Collections.singletonList("key"),  Collections.singletonList("value"))`

an error got...

> org.luaj.vm2.LuaError: script:1 vm error: java.lang.NullPointerException

**Comment by chenjianboKeyboard** [comment]
version 1.6.0

**Comment by tonivade** [comment]
I'm working on it

**Comment by tonivade** [comment]
Hi, can you try the latest snapshot with the fix?

- First clone the claudb repository
- Then run `./gradlew clean install`
- Set the version `1.7.0-SNAPSHOT` in your project, and run the tests.

Thanks!
